
/***************************************************************************************************
| H | O | R | I | Z | O | N |   | L | A | B | S | 

Demo:         Horizon Lab
Version:      HLab v2.0
Create Date:  Apr 17, 2024
Author:       Ravi Kumar
Reviewers:    Ben Weiss, Susan Devitt
Contributor:  Severin Gassauer (severin.gassauer@snowflake.com)
Copyright(c): 2026 Snowflake Inc. All rights reserved.
****************************************************************************************************/
/****************************************************************************************************
SUMMARY OF CHANGES
Date(yyyy-mm-dd)    Author              Comments
------------------- ------------------- ------------------------------------------------------------
Apr 17, 2024        Ravi Kumar          Initial Lab
Jan 26, 2026        Severin Gassauer    Added AI Governance Extension privileges
***************************************************************************************************/


--Create all Roles and assign to user
USE ROLE LOCAL_ADMIN;
CREATE OR REPLACE ROLE HRZN_NABS_DATA_ENGINEER;
CREATE OR REPLACE ROLE HRZN_NABS_DATA_GOVERNOR;
CREATE OR REPLACE ROLE HRZN_NABS_DATA_USER;
CREATE OR REPLACE ROLE HRZN_NABS_IT_ADMIN;

GRANT ROLE HRZN_NABS_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE HRZN_NABS_DATA_GOVERNOR TO ROLE SYSADMIN;
GRANT ROLE HRZN_NABS_DATA_USER TO ROLE SYSADMIN;
GRANT ROLE HRZN_NABS_IT_ADMIN TO ROLE SYSADMIN;

SET MY_USER_ID  = CURRENT_USER();
SELECT ($MY_USER_ID);
GRANT ROLE HRZN_NABS_DATA_ENGINEER TO USER "NABOU.DIENGSTRIFE@SLALOM.COM";
GRANT ROLE HRZN_NABS_DATA_GOVERNOR TO USER "NABOU.DIENGSTRIFE@SLALOM.COM";
GRANT ROLE HRZN_NABS_DATA_USER TO USER "NABOU.DIENGSTRIFE@SLALOM.COM";
GRANT ROLE HRZN_NABS_IT_ADMIN TO USER "NABOU.DIENGSTRIFE@SLALOM.COM";

--Create warehouse and provide grants
USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE HRZN_NABS_WH WITH WAREHOUSE_SIZE='X-SMALL';
GRANT USAGE ON WAREHOUSE HRZN_NABS_WH TO ROLE HRZN_NABS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HRZN_NABS_WH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT USAGE ON WAREHOUSE HRZN_NABS_WH TO ROLE HRZN_NABS_DATA_USER;
GRANT USAGE ON WAREHOUSE HRZN_NABS_WH TO ROLE HRZN_NABS_IT_ADMIN;

--Create database, schemas and assign to appropriate roles
-- NOTE: Using SYSADMIN instead of ACCOUNTADMIN (not available to this user).
-- SYSADMIN creates the DB, then transfers ownership to HRZN_NABS_DATA_ENGINEER.

USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE HRZN_NABS_DB;
CREATE OR REPLACE SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH;

-- Transfer ownership so HRZN_NABS_DATA_ENGINEER can manage its own objects
GRANT OWNERSHIP ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA HRZN_NABS_DB.PUBLIC TO ROLE HRZN_NABS_DATA_ENGINEER COPY CURRENT GRANTS;

-- Now grant from HRZN_NABS_DATA_ENGINEER (the owner)
USE ROLE HRZN_NABS_DATA_ENGINEER;

GRANT USAGE ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT USAGE ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT CREATE SCHEMA ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_GOVERNOR;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT ON ALL TABLES IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;

GRANT USAGE ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_IT_ADMIN;
GRANT USAGE ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_IT_ADMIN;
GRANT CREATE SCHEMA ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_IT_ADMIN;

GRANT USAGE ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_USER;
GRANT USAGE ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_USER;
GRANT SELECT ON ALL TABLES IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_USER;

USE ROLE HRZN_NABS_DATA_GOVERNOR;

-- Create a  Schema to contain classifiers
CREATE OR REPLACE SCHEMA HRZN_NABS_DB.CLASSIFIERS
COMMENT = 'Schema containing Classifiers';

-- Create a Schema to contain Tags
CREATE OR REPLACE SCHEMA HRZN_NABS_DB.TAG_SCHEMA
COMMENT = 'Schema containing Tags';

CREATE OR REPLACE TABLE HRZN_NABS_DB.TAG_SCHEMA.ROW_POLICY_MAP
    (role STRING, state_visibility STRING);

-- with the table in place, we will now INSERT the relevant Role to State Permissions mapping to ensure
-- our Test Role can only see Massachusetts (MA) customers
INSERT INTO HRZN_NABS_DB.TAG_SCHEMA.ROW_POLICY_MAP
    VALUES ('HRZN_NABS_DATA_USER','MA'); 

select * from HRZN_NABS_DB.TAG_SCHEMA.ROW_POLICY_MAP;

    
-- Create a Schema to contain Security Policies
CREATE OR REPLACE SCHEMA SEC_POLICIES_SCHEMA
COMMENT = 'Schema containing Security Policies';

USE ROLE HRZN_NABS_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_GOVERNOR;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_USER;
GRANT SELECT ON FUTURE TABLES IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_USER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_IT_ADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_IT_ADMIN;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_IT_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_IT_ADMIN;
GRANT SELECT ON ALL VIEWS IN DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_IT_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_IT_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_IT_ADMIN;


-- ==========================================================================
-- REQUIRES ACCOUNTADMIN: Ask your account admin to run this block separately
-- ==========================================================================
-- USE ROLE ACCOUNTADMIN;
-- GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_NABS_DATA_ENGINEER;
-- GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_NABS_DATA_ENGINEER;
-- GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE HRZN_NABS_IT_ADMIN;
-- GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE HRZN_NABS_IT_ADMIN;
-- GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE HRZN_NABS_IT_ADMIN;
-- GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_NABS_IT_ADMIN;
-- GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_NABS_IT_ADMIN;



/***** C R E A T E   T A B L E *******/

USE ROLE HRZN_NABS_DATA_ENGINEER;
CREATE OR REPLACE TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER (
	ID FLOAT,
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	STREET_ADDRESS VARCHAR,
	STATE VARCHAR,
	CITY VARCHAR,
	ZIP VARCHAR,
	PHONE_NUMBER VARCHAR,
	EMAIL VARCHAR,
	SSN VARCHAR,
	BIRTHDATE VARCHAR,
	JOB VARCHAR,
	CREDITCARD VARCHAR,
	COMPANY VARCHAR,
	OPTIN VARCHAR
);
CREATE OR REPLACE TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS (
    CUSTOMER_ID VARCHAR,	
    ORDER_ID VARCHAR,	
    ORDER_TS DATE,	
    ORDER_CURRENCY VARCHAR,	
    ORDER_AMOUNT FLOAT,	
    ORDER_TAX FLOAT,	
    ORDER_TOTAL FLOAT
);
-- Load data from S3 into target tables. Then perform GRANTs.
COPY INTO HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER
FROM s3://sfquickstarts/summit_2024_horizon_hol/CustomerDataRaw.csv
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1)
;

COPY INTO HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS
FROM s3://sfquickstarts/summit_2024_horizon_hol/CustomerOrders.csv
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1)
;
GRANT ALL ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER TO ROLE HRZN_NABS_DATA_USER;
GRANT SELECT ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER TO ROLE HRZN_NABS_IT_ADMIN;

GRANT ALL ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS TO ROLE HRZN_NABS_DATA_USER;
GRANT SELECT ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS TO ROLE HRZN_NABS_IT_ADMIN;



-- ==========================================================================
-- REQUIRES ACCOUNTADMIN: Ask your account admin to run this block separately
-- ==========================================================================
-- USE ROLE ACCOUNTADMIN;
-- GRANT APPLY TAG on ACCOUNT to ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT APPLY MASKING POLICY on ACCOUNT to ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT APPLY AGGREGATION POLICY ON ACCOUNT TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT APPLY PROJECTION POLICY ON ACCOUNT TO ROLE HRZN_NABS_DATA_GOVERNOR;
-- GRANT DATABASE ROLE SNOWFLAKE.CLASSIFICATION_ADMIN TO ROLE HRZN_NABS_DATA_GOVERNOR;

--USE ROLE HRZN_NABS_DATA_ENGINEER;
--truncate table HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER;
--truncate table HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS;

--Create View for Semantic Models and Analysis
USE ROLE HRZN_NABS_DATA_ENGINEER;
use database HRZN_NABS_DB;
use schema HRZN_NABS_DB.HRZN_NABS_SCH;
USE WAREHOUSE HRZN_NABS_WH;

-- Create summary view for customer order analytics
CREATE OR REPLACE VIEW HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDER_SUMMARY AS
SELECT C.ID, C.FIRST_NAME, C.LAST_NAME, COUNT(CO.ORDER_ID) ORDERS_COUNT, SUM(CO.ORDER_TOTAL) ORDER_TOTAL
FROM HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER C, HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS CO
WHERE C.ID  = CO.CUSTOMER_ID
GROUP BY 1,2,3;

-- ============================================================================
-- AI GOVERNANCE EXTENSION PRIVILEGES
-- ============================================================================
-- These grants enable sections 4-6 (Semantic Views, AI_REDACT, NL Governance)
-- Added for AI Governance Lab Extensions
-- ============================================================================

-- AI GOVERNANCE EXTENSION PRIVILEGES: object-level grants via DB owner
USE ROLE HRZN_NABS_DATA_ENGINEER;

-- Section 4: Semantic View Governance
GRANT CREATE SEMANTIC VIEW ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT CREATE VIEW ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_NABS_DB.HRZN_NABS_SCH.CUSTOMER_ORDERS TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT CREATE SCHEMA ON DATABASE HRZN_NABS_DB TO ROLE HRZN_NABS_DATA_GOVERNOR;

-- Section 5: AI-Powered Classification
GRANT CREATE FUNCTION ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT CREATE PROCEDURE ON SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT USAGE ON SCHEMA HRZN_NABS_DB.CLASSIFIERS TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT CREATE FUNCTION ON SCHEMA HRZN_NABS_DB.CLASSIFIERS TO ROLE HRZN_NABS_DATA_GOVERNOR;

-- Allow roles to use Cortex functions
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_GOVERNOR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_DATA_USER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HRZN_NABS_DB.HRZN_NABS_SCH TO ROLE HRZN_NABS_IT_ADMIN;

-- ==========================================================================
-- REQUIRES ACCOUNTADMIN: Ask your account admin to run these two commands
-- ==========================================================================
-- ALTER ACCOUNT SET CORTEX_MODELS_ALLOWLIST = 'All';
-- ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

SELECT 'Lab setup complete. You can now run sections 1-6.' as status;
